name: ssb_youth_tiger
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.5
  shared_preferences: ^2.0.8
  image_picker: ^0.8.4+4
  file_picker: ^6.0.0
  intl: ^0.18.0
  weather: ^3.0.0
  flutter_svg: ^2.0.9
  shimmer: ^2.0.0
  google_fonts: ^2.0.0
  lottie: ^2.0.0
  cached_network_image: ^3.0.0
  flutter_local_notifications: ^10.0.0
  flutter_image_compress: ^2.0.0
  workmanager: ^0.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  # Sementara comment dulu fonts sampai file font tersedia
  # fonts:
  #   - family: Poppins
  #     fonts:
  #       - asset: assets/fonts/Poppins-Regular.ttf
  #       - asset: assets/fonts/Poppins-Medium.ttf
  #         weight: 500
  #       - asset: assets/fonts/Poppins-SemiBold.ttf
  #         weight: 600
  #       - asset: assets/fonts/Poppins-Bold.ttf
  #         weight: 700
