name: uasmanager
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  table_calendar: ^3.0.0
  http: ^1.1.0
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.0.10
  intl: ^0.18.0
  calendar_date_picker2: ^0.5.3
  image_picker: ^1.0.4
  flutter_staggered_grid_view: ^0.7.0
  carousel_slider: ^4.2.1
  animated_text_kit: ^4.2.2
  lottie: ^2.7.0
  flutter_staggered_animations: ^1.1.1
  flutter_slidable: ^3.0.1
  share_plus: ^7.2.2
  url_launcher: ^6.2.5
  url_launcher_android: ^6.2.5
  url_launcher_ios: ^6.2.5
  url_launcher_linux: ^3.1.1
  url_launcher_macos: ^3.1.0
  url_launcher_web: ^2.2.3
  url_launcher_windows: ^3.1.1
  qr_flutter: ^4.1.0
  font_awesome_flutter: ^10.7.0
  supabase_flutter: ^2.3.4
  shimmer: ^3.0.0
  mime: ^1.0.4
  http_parser: ^4.0.2



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
